# Generated by Django 3.2.25 on 2025-10-24 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('credit_card', 'Credit Card')], help_text='Payment method used', max_length=20)),
                ('date', models.DateField(help_text='Date when payment was made')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='paid', help_text='Current status of the payment', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference or transaction ID', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='clients.client')),
                ('collector', models.ForeignKey(blank=True, help_text='Collector who processed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to='collectors.collector')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'db_table': 'payment_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['client'], name='payment_rec_client__41a9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['date'], name='payment_rec_date_51eea4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status'], name='payment_rec_status_83cf06_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['collector'], name='payment_rec_collect_af978f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['mode'], name='payment_rec_mode_7512f5_idx'),
        ),
    ]
