apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genieacs.fullname" . }}
  labels:
    {{- include "genieacs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "genieacs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "genieacs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: GENIEACS_MONGODB_CONNECTION_URL
              value: "{{ .Values.mongodb.connectionURL | default (printf "mongodb://%s-mongodb/%s" (include "genieacs.fullname" .) "genieacs") }}"
          ports:
            - name: http
              containerPort: {{ .Values.service_http.port_http }}
            - name: cwmp
              containerPort: {{ .Values.service_cwmp.port_cwmp }}
            - name: nbi
              containerPort: {{ .Values.service_nbi.port_nbi }}
            - name: fs
              containerPort: {{ .Values.service_fs.port_fs }}
          volumeMounts:
            - name: opt-volume
              mountPath: /opt
          resources:
            limits:
              {{- toYaml .Values.resources.limits | nindent 12 }}
            requests:
              {{- toYaml .Values.resources.requests | nindent 12 }}
      volumes:
        - name: opt-volume
          persistentVolumeClaim:
            claimName: {{ include "genieacs.fullname" . }}-pvc
      restartPolicy: Always