# Generated by Django 3.2.25 on 2025-10-24 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatusReport',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='Date when the report was generated')),
                ('total_accounts', models.PositiveIntegerField(help_text='Total number of accounts')),
                ('active_accounts', models.PositiveIntegerField(help_text='Number of active accounts')),
                ('overdue_accounts', models.PositiveIntegerField(help_text='Number of overdue accounts')),
                ('disconnected_accounts', models.PositiveIntegerField(help_text='Number of disconnected accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Status Report',
                'verbose_name_plural': 'Account Status Reports',
                'db_table': 'account_status_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectorPerformance',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start date of the performance period')),
                ('period_end', models.DateField(help_text='End date of the performance period')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount collected during the period', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('clients_served', models.PositiveIntegerField(default=0, help_text='Number of clients served during the period')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average performance rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collector Performance',
                'verbose_name_plural': 'Collector Performance Records',
                'db_table': 'collector_performance',
                'ordering': ['-period_end', '-collected_amount'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month of the collection (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField(help_text='Year of the collection')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount collected for the month', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Collection',
                'verbose_name_plural': 'Monthly Collections',
                'db_table': 'monthly_collections',
                'ordering': ['year', 'month'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlycollection',
            index=models.Index(fields=['year', 'month'], name='monthly_col_year_305623_idx'),
        ),
        migrations.AddField(
            model_name='collectorperformance',
            name='collector',
            field=models.ForeignKey(help_text='Collector whose performance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='collectors.collector'),
        ),
        migrations.AddIndex(
            model_name='accountstatusreport',
            index=models.Index(fields=['report_date'], name='account_sta_report__79d6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorperformance',
            index=models.Index(fields=['collector'], name='collector_p_collect_76144c_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorperformance',
            index=models.Index(fields=['period_start', 'period_end'], name='collector_p_period__fd6087_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorperformance',
            index=models.Index(fields=['collected_amount'], name='collector_p_collect_7efb7c_idx'),
        ),
    ]
