# Generated by Django 3.2.25 on 2025-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=120)),
                ('plan', models.CharField(choices=[('fiber_30', 'Fiber 30Mbps'), ('fiber_50', 'Fiber 50Mbps'), ('fiber_100', 'Fiber 100Mbps')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('router_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_payment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_name_0bc5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['town'], name='clients_town_4bdf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['plan'], name='clients_plan_f53aee_idx'),
        ),
    ]
