# Generated by Django 3.2.25 on 2025-10-24 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.CharField(help_text='Unique router identifier (e.g., R001, R002, R003)', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', help_text='Current operational status of the router', max_length=12)),
                ('uptime', models.DurationField(blank=True, help_text='Duration the router has been continuously operational', null=True)),
                ('signal_strength', models.FloatField(blank=True, help_text='Signal strength in dBm (typically -120 to -30)', null=True, validators=[django.core.validators.MinValueValidator(-120), django.core.validators.MaxValueValidator(-30)])),
                ('location', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], help_text='Physical or logical location of the router', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time the router was seen online', null=True)),
                ('client', models.ForeignKey(help_text='Client associated with this router', on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='clients.client')),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'db_table': 'routers',
                'ordering': ['router_id'],
            },
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['router_id'], name='routers_router__2fc653_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['status'], name='routers_status_7f5b80_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['location'], name='routers_locatio_dd3dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['client'], name='routers_client__8bedc2_idx'),
        ),
    ]
