# Generated by Django 3.2.25 on 2025-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_town', models.CharField(max_length=120)),
                ('active_clients', models.PositiveIntegerField(default=0)),
                ('last_collection_date', models.DateField(blank=True, null=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 score used to render the progress bar', max_digits=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
                'db_table': 'collectors',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['name'], name='collectors_name_1df7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['assigned_town'], name='collectors_assigne_e15144_idx'),
        ),
    ]
